module CLKGATETST_X1 (
  input CK,
  input E,
  input SE,
  output GCK
);

  reg  enable_latch_q;

  // Behavioral model for a glitch-free clock gating cell.
  // The enable signal 'E' is latched (captured) when the clock 'CK' is low.
  // This ensures that 'E' can change asynchronously during the low phase of 'CK'
  // without creating glitches on 'GCK' during the high phase.
  always @(CK or E) begin
    if (!CK) begin // When CK is low, the latch is transparent
      enable_latch_q <= E;
    end
    // When CK is high, enable_latch_q holds its value, making the latch opaque.
  end

  // The gated clock 'GCK' is generated by ANDing the input clock 'CK'
  // with either the latched enable 'enable_latch_q' or the test enable 'SE'.
  // If 'SE' (Test Enable) is high, the clock gate is effectively always open
  // (subject to the clock 'CK' itself), bypassing the enable latch.
  // If 'SE' is low, 'GCK' follows 'CK' only when 'enable_latch_q' is high.
  assign GCK = CK & (enable_latch_q | SE);

endmodule
