module CLKGATETST_X1 (
  input CK,
  input E,
  input SE,
  output GCK
);

  reg en_latch_q;

  // Behavioral model for a high-active clock gating latch:
  // The latch for the enable signal 'E' is level-sensitive.
  // It is transparent when the clock 'CK' is low, capturing the value of 'E'.
  // When 'CK' is high, the latch holds its current value.
  always @(E or CK) begin
    if (!CK) begin // Latch is transparent when CK is low
      en_latch_q = E;
    end
    // When CK is high, en_latch_q holds its value.
  end

  // The gated clock 'GCK' is generated by ANDing 'CK' with the latched enable.
  // The 'SE' (Test Enable) signal acts as an override, forcing the clock gate open
  // (i.e., propagating 'CK') regardless of the latched enable, if 'SE' is high.
  assign GCK = CK & (en_latch_q | SE);

endmodule
