// Behavioral definition for the CLKGATETST_X1 clock gate primitive
// This model implements a glitch-free clock gate with a high-active enable (E)
// and a test enable (SE) that overrides the normal enable.
// The enable signal 'E' is internally latched by a negative-level sensitive latch
// to ensure clean gating of the clock 'CK'.
module CLKGATETST_X1 (CK, E, SE, GCK);
  input CK, E, SE;
  output GCK;

  reg en_q; // Internal latch to hold the enable signal

  // Latch the enable signal 'E' when 'CK' is low (negative-level sensitive latch).
  // This mechanism is key for glitch-free clock gating: 'en_q' can only change
  // when 'CK' is low, preventing 'GCK' from having spurious transitions when 'CK' is high.
  always @(CK or E) begin
    if (!CK) begin // When CK is low, the latch is transparent and captures 'E'
      en_q <= E;
    end
    else begin // When CK is high, 'en_q' holds its last value. Making this explicit.
      en_q <= en_q;
    end
  end

  // The gated clock 'GCK' is generated by ANDing 'CK' with the effective enable.
  // The effective enable is high if 'SE' (Test Enable) is high (overriding 'E'),
  // OR if the latched normal enable 'en_q' is high.
  assign GCK = CK & (SE | en_q);

endmodule
