module SNPS_CLOCK_GATE_HIGH_REG_NBIT15_18_0 ( CLK, EN, ENCLK, TE );

  input CLK, EN, TE;
  output ENCLK;

  wire en_combined = EN & TE; // Combined enable signal
  reg  en_latch;              // Latch to hold the combined enable

  // This always block infers a level-sensitive latch for 'en_latch'.
  // The latch is transparent when CLK is low and holds its value when CLK is high.
  always @(en_combined or CLK) begin
    if (!CLK) begin // When CLK is low, the latch is transparent
      en_latch = en_combined;
    end
    // Else (when CLK is high), en_latch holds its previous value,
    // thus implementing a negative-level transparent latch.
  end

  // The gated clock (ENCLK) is generated by ANDing the main clock (CLK)
  // with the latched enable signal (en_latch). This is a standard
  // clock gating scheme that ensures a glitch-free output clock.
  assign ENCLK = CLK & en_latch;

endmodule
