module CLKGATETST_X1 (
  input CK,
  input E,
  input SE,
  output GCK
);

  reg en_latched_q; // Output of the enable latch

  // This always block implements a negative-level sensitive transparent latch.
  // When the clock (CK) is low, the latch is transparent, and 'en_latched_q' follows 'E'.
  // When CK is high, the latch holds the last value of 'E' captured when CK was low.
  always @(E or CK) begin
    if (!CK) begin
      en_latched_q = E;
    end
  end

  // The gated clock (GCK) is generated by ANDing the clock (CK) with the enable logic.
  // The enable logic is either the latched enable ('en_latched_q') or the test enable ('SE').
  // If 'SE' (Test Enable) is high, it bypasses the normal enable and allows GCK to follow CK.
  assign GCK = CK && (en_latched_q || SE);

endmodule
