module CLKGATETST_X1 (
  input CK,  // Main clock input
  input E,   // Functional enable input
  input SE,  // Test enable input
  output GCK // Gated clock output
);

  // Internal signal for the latched enable
  reg latched_en;

  // Combine functional enable (E) and test enable (SE).
  // Assuming SE is an active-high test enable that can override or be ORed with E.
  wire combined_en = E | SE;

  // Implement a transparent latch for the enable signal.
  // This latch is transparent (follows 'combined_en') when CK is low.
  // It holds its value when CK is high. This is a common behavior for
  // the enable latch in a clock gating cell, ensuring the enable is
  // stable before the rising edge of the main clock (CK).
  always @(*) begin
    if (!CK) begin // Latch is transparent when CK is low
      latched_en = combined_en;
    end
    // When CK is high, the latch holds its current value (implied by 'reg' and lack of 'else')
  end

  // The gated clock (GCK) is generated by ANDing the main clock (CK)
  // with the latched enable (latched_en).
  assign GCK = CK & latched_en;

endmodule
