module CLKGATETST_X1 (CK, E, SE, GCK);
  input CK, E, SE;
  output GCK;

  reg en_q; // Output of the enable latch

  // Behavioral model for a negative-level sensitive latch for enable 'E'
  // The latch is transparent when CK is low, capturing the value of E.
  // It holds its value when CK is high.
  always @(E or negedge CK) begin
    if (~CK) begin // If CK is low, latch is transparent
      en_q <= E;
    end
  end

  // The final gated clock (GCK) is generated by ANDing the input clock (CK)
  // with the latched enable (en_q) OR the test enable (SE).
  // This ensures that the gated clock is high only when the input clock is high
  // AND the gate is enabled (either by E through the latch, or by SE).
  assign GCK = CK & (en_q | SE);

endmodule
