module curve_synth_5284_20260111_220510_406590_w15680_attempt11 (
  input [1:0] sel_in,
  output reg out_reg
);

  // SYNTH_5284: Non synthesizable construct: floating point type constant
  // This rule is triggered when floating point literals are used as case item expressions.
  // Occurrences 1 and 2 are generated by the two floating point constants in the case statement.
  always @* begin
    case (sel_in) // 'sel_in' is an integer type
      1.5: out_reg = 1'b1; // Occurrence 1: Floating point constant as case item
      2.5: out_reg = 1'b0; // Occurrence 2: Floating point constant as case item
      default: out_reg = 1'b0;
    endcase
  end

endmodule
