`timescale 1ns / 1ps

module clockgenmodule (input i_clk, input i_rst_n, output clk_out);
 // Original clk_out period was 10 time units (5 high, 5 low).
 // To preserve this functional behavior in a synthesizable manner, 
 // we introduce a master clock (i_clk) and a reset (i_rst_n).
 // Assuming i_clk has a period of 1 time unit (generated by top_module's #0.5 toggle),
 // we need to count 5 i_clk cycles for each half-period of clk_out.
 // This results in clk_out toggling every 5 i_clk cycles, yielding a period of 10 i_clk cycles.
 // With `timescale 1ns / 1ps`, a 1-time-unit i_clk period means clk_out period is 10ns.

 reg clk_reg;
 reg [2:0] counter; // Needs to count from 0 to 4 (5 states)

 always @(posedge i_clk or negedge i_rst_n) begin
   if (!i_rst_n) begin
     clk_reg <= 1'b0;
     counter <= 3'b000;
   end else begin
     if (counter == 3'd4) begin // Count 5 i_clk cycles (0,1,2,3,4)
       clk_reg <= ~clk_reg;
       counter <= 3'b000;
     end else begin
       counter <= counter + 3'b001;
     end
   end
 end

 assign clk_out = clk_reg;
endmodule
